name: Deploy to mondal.in

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Install and Build
      uses: actions/setup-node@v3
      with:
        node-version: 14
      run: npm install
      run: npm run build

    - name: Deploy
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        ftp-server: ${{ secrets.FTP_SERVER }}
        ftp-username: ${{ secrets.FTP_USER }}
        local-dir: dist/guitar/
        ftp-password: ${{ secrets.FTP_PASSWORD }}